---

# Hosts need to be configured yet -- Check this out first
- hosts: nodes
  become: yes


  vars:
    - homeDir: home # Configure our home directory
    - appDir : app
    - repo: bot
  

  tasks:
  - name: Install Packages
    apt: name={{ item }} update_cache=yes state=latest
    with_items:
      - npm
      - nodejs-legacy
      - git
      - curl

  - name: Create APP Directory
    file: path={{homeDir}}/{{appDir}} state=directory

  # - name: ensure required packages are installed for Java 7
  #   apt: name=$item state=latest update_cache=yes
  #   with_items:
  #     - python-software-properties

  # - name: Add Java repository to sources
  #   action: apt_repository repo='ppa:webupd8team/java'

  # - name: Autoaccept license for Java
  #   action: shell echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
 
  # - name: Update APT package cache
  #   action: apt update_cache=yes

  # - name: Install Java 8
  #   action: apt pkg=oracle-java8-installer state=latest install_recommends=yes

  # - name: Set Java 8 Env
  #   action: apt pkg=oracle-java8-set-default state=latest install_recommends=yes

  - name: Install forever
    npm: name=forever global=yes state=present
    become: yes

  - name: Get root previlige
    command: sudo su

  - name: Set map count
    command: sysctl -w vm.max_map_count=262144

  - name: Set maximum file size
    command: sysctl -w fs.file-max=65536

  # - name: Set upper limit
  #   command: ulimit -n 65536

  - name: Clone repo
    git:
      repo: git@github.ncsu.edu:rcoutin/BOT.git
      dest: /home/vagrant/BOT
      key_file: code/Playbooks/id_rsa
      accept_hostkey: yes
      force: yes

  - name: Running NPM install
    npm: path={{homeDir}}/{{appDir}}/backened
    register: npm_finished
    when: git_finished.changed

  # Stop the application if previous instance is running
  - name: Stop APP
    sudo_user: ubuntu
    command: pm2 stop app chdir={{homeDir}}/{{appDir}}/backened
    ignore_errors: yes

  - name: Start APP
    sudo_user: ubuntu
    command: pm2 start index.js --name app chdir={{homeDir}}/{{appDir}}/backened
    ignore_errors: yes
    when: npm_finished.changed


    
